### ISSUE TITLE
test image problem for "Cityscapes" 

### ISSUE THREAD

**Issue by jsonw99** [ndrplz/dilation-tensorflow#1]
hi @ndrplz,

when i replaced the "cityscapes.png" file in the data directory by some other test image with smaller resolution (e.g. 1438 x 803), then I got following error:
```bash  
File "main_tf.py", line 61, in <module>
    predicted_image = predict(input_image, input_tensor, model, dataset, sess)
  File "C:\Users\ininetynine\Desktop\dilation-tensorflow-master\utils.py", line 79, in predict
    color_image = CONFIG[ds]['palette'][prediction.ravel()].reshape(image_size)
ValueError: total size of new array must be unchanged
```
any idea on the reason behind this? and how should i fix it? thank you ~

**Comment by ndrplz** [comment]
Hi @jsonw99,

looks like your `prediction` has a different size from your input image size `image_size`, so it complains when you try to reshape it to that shape.

As you can notice the prediction is performed tile by tile, then all tiles are concatenated (see [here](https://github.com/ndrplz/dilation-tensorflow/blob/bf51fe1ac5dda250e0795d4b8afbd134ba5a485e/utils.py#L41-L70)). This is the way it was performed in the original caffe repo too. This indeed gave me some headache in the past.

I can only suggest to debug line-by-line the tiling part and see which are the dimensions involved in your case. Hopefully you can change the padding / tiling appropriately to find a solution for your case.

**Comment by jsonw99** [comment]
thanks @ndrplz, appreciated. have a nice thanks giving.
