### ISSUE TITLE
ResourceExhaustedError - Jetson TX1

### ISSUE THREAD

**Issue by kaisark** [ndrplz/dilation-tensorflow#2]
I ran into a ResourceExhaustedError errror on my Jetson TX1 with 4GB of RAM. How much RAM is needed/recommended to test the code???

Ubuntu 16.04
python 3.5
tensorflow 1.5.0
cv2 3.3.0
pretrained_dilation_cityscapes.pickle - 537MB

------------------------------------------
ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [7,7,512,4096] and type float
	 \[\[Node: fc6/Variable/initial_value \= Const\[dtype=DT_FLOAT, value=Tensor<type: float shape: [7,7,512,4096] values: [[[-4.46356426e-05 0.000302301254 -0.00146040611]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by ndrplz** [comment]
Hi @kaisark,

I can run the forward inference on a Quadrok2200 with 4GB of memory.

Are you trying to train the model or just using the pretrained one frozen for inference? Since during training your memory footprint is much bigger.

**Comment by AFIDclan** [comment]
I'm running into the same problem and I'm not training the network. Just running it.

GPU: NVIDIA GeForce GTX 1060 3GB
8 GB of RAM

Running it on a windows desktop

**Comment by AFIDclan** [comment]
Is it possible that the pickle may have been updated and is now larger?

**Comment by ndrplz** [comment]
The pickle containing pre-trained weights was never updated since the first release on this repo.

The weird thing is that I tried today on my Quadro (I have not used this model recently) and it goes indeed in OOM.
