### ISSUE TITLE
Utils.py raises ValueError: cannot reshape array of size 50331648 into shape (3183,3183,3)

### ISSUE THREAD

**Issue by jin-zhe** [ndrplz/dilation-tensorflow#3]
`main_tf.py` with pre-trained Cityscapes weights works with no problems when I run it on the dummy image under `/data`.
However when I ran it on my [own image here](https://imgur.com/a/hNAME), I encountered the following error:
```sh
Traceback (most recent call last):
  File "main_tf.py", line 60, in <module>
    predicted_image = predict(input_image, input_tensor, model, dataset, sess)
  File "dilation-tensorflow/utils.py", line 76, in predict
    color_image = CONFIG[ds]['palette'][prediction.ravel()].reshape(image_size)
ValueError: cannot reshape array of size 50331648 into shape (3183,3183,3)
```
`50331648` corresponds to a shape of `(4096,4096,3)` which is not the image size. What might be the issue here?

**Comment by ndrplz** [comment]
Hi @jin-zhe, did you take a look to this #1 ?
